### ISSUE TITLE
Random Grade doesn't give me a student when pool is nonempty

### ISSUE THREAD

**Issue by jonathanFinnell** [robojeb/HMC-Grader#11]
Title says it all. Attached image
![capture](https://cloud.githubusercontent.com/assets/6056058/5914122/b6d01100-a5a4-11e4-96d6-efcb7bee4b4a.PNG)

**Comment by robojeb** [comment]
According to the randomizer the pool is empty because those submissions haven't gone through the autograder yet. Once they do that they say (Tested, Ungraded). This is not a bug in the randomizer but a bug in the autograder that I am working on.
